### ISSUE TITLE
Cannot locate downloaded model in model cache when running `python gradio_chat.py --baseonly` local inference

### ISSUE THREAD

**Issue by sirredbeard** [microsoft/vscode-ai-toolkit#96]
```
(phi-3-env) hayden@XPS15:/mnt/d/phi3-finetuning/phi3-finetuning/terminal-assistant/inference$ python gradio_chat.py --baseonly
Number of GPUs available: 1
Running on device: cuda
CPU threads: 10
Traceback (most recent call last):
  File "/opt/miniconda/envs/phi-3-env/lib/python3.9/site-packages/transformers/utils/hub.py", line 399, in cached_file
    resolved_file = hf_hub_download(
  File "/opt/miniconda/envs/phi-3-env/lib/python3.9/site-packages/huggingface_hub/utils/_deprecation.py", line 101, in inner_f
    return f(*args, **kwargs)
  File "/opt/miniconda/envs/phi-3-env/lib/python3.9/site-packages/huggingface_hub/utils/_validators.py", line 106, in _inner_fn
    validate_repo_id(arg_value)
  File "/opt/miniconda/envs/phi-3-env/lib/python3.9/site-packages/huggingface_hub/utils/_validators.py", line 154, in validate_repo_id
    raise HFValidationError(
huggingface_hub.errors.HFValidationError: Repo id must be in the form 'repo_name' or 'namespace/repo_name': '../model-cache/microsoft/Phi-3-mini-4k-instruct'. Use `repo_type` argument if needed.

The above exception was the direct cause of the following exception:

  File "/mnt/d/phi3-finetuning/phi3-finetuning/terminal-assistant/inference/gradio_chat.py", line 40, in <module>
    tokenizer = load_tokenizer(model_name)
  File "/mnt/d/phi3-finetuning/phi3-finetuning/terminal-assistant/inference/utils.py", line 38, in load_tokenizer
    tok = AutoTokenizer.from_pretrained(model_name, device_map=get_device_map(), trust_remote_code=True)
  File "/opt/miniconda/envs/phi-3-env/lib/python3.9/site-packages/transformers/models/auto/tokenization_auto.py", line 817, in from_pretrained
    tokenizer_config = get_tokenizer_config(pretrained_model_name_or_path, **kwargs)
  File "/opt/miniconda/envs/phi-3-env/lib/python3.9/site-packages/transformers/models/auto/tokenization_auto.py", line 649, in get_tokenizer_config
    resolved_config_file = cached_file(
  File "/opt/miniconda/envs/phi-3-env/lib/python3.9/site-packages/transformers/utils/hub.py", line 463, in cached_file
    raise EnvironmentError(
OSError: Incorrect path_or_model_id: '../model-cache/microsoft/Phi-3-mini-4k-instruct'. Please provide either the path to a local folder or the repo_id of a model on the Hub.
(phi-3-env) hayden@XPS15:/mnt/d/phi3-finetuning/phi3-finetuning/terminal-assistant/inference$
```

**Comment by sirredbeard** [comment]
It appears AI Toolkit simply didn't download the model. Started over from scratch, it downloaded.
